development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reaio_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reaio_test
  pool: 5
  username: root
  password: 


production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: reaio_production
  username: root
  password: 